### Get All Notes
GET http://localhost:3010/api/v1/notes

### Get Note by ID
GET http://localhost:3010/api/v1/notes/6

### Create Note
POST http://localhost:3010/api/v1/notes
Content-Type: application/json

{
  "judul": "Catatan Pertama",
  "isi": "Ini adalah isi catatan pertama saya"
}

### Create Another Note
POST http://localhost:3010/api/v1/notes
Content-Type: application/json

{
  "judul": "Catatan Kedua",
  "isi": "Ini adalah isi catatan kedua saya"
}

### Update Note
PUT http://localhost:3010/api/v1/notes/9
Content-Type: application/json

{
  "judul": "tes (Updated)",
  "isi": "Isi catatan pertama yang sudah diupdate"
}

### Delete Note
DELETE http://localhost:3010/api/v1/notes/9
